# Generated by Django 6.0 on 2026-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_category_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('romance', 'Romance'), ('comedy', 'Comedy'), ('action', 'Action'), ('thriller', 'Thriller'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('family', 'Family'), ('fantasy', 'Fantasy')], max_length=50),
        ),
    ]
